// <auto-generated />
using System;
using MaxEndLabs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaxEndLabs.Data.Migrations.PostgresMigrations
{
    [DbContext(typeof(MaxEndLabsDbContext))]
    [Migration("20260406161410_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaxEndLabs.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("06313180-fa45-42b5-ac33-1333f673455d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bfdb153-a446-4968-a40f-34adc37a6f28",
                            Email = "admin@labs.com",
                            EmailConfirmed = true,
                            FullName = "Dimitar Ivanov Berbatov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LABS.COM",
                            NormalizedUserName = "ADMIN@LABS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP9JzX0YwKm6N+luPkuHrobdVlv+8FQxWWME12rmICorZgnbmrHziPC+5WxRG5/6aw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c0142471-6ffd-44b4-b430-8b3c7acf8fbf",
                            TwoFactorEnabled = false,
                            UserName = "admin@labs.com"
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("CartId", "ProductId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb8ceb6a-6623-4937-a6c4-777b4b498e1e"),
                            Name = "Upper Body",
                            Slug = "upper-body"
                        },
                        new
                        {
                            Id = new Guid("6f026985-b5c2-4b05-9ac4-088b88982ec8"),
                            Name = "Lower Body",
                            Slug = "lower-body"
                        },
                        new
                        {
                            Id = new Guid("a9c9243a-aca9-4d3c-8f7a-4bdeb4578682"),
                            Name = "Shoes",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = new Guid("f1f47314-cdc4-4104-a9f2-a2ccf38e9623"),
                            Name = "Supplements",
                            Slug = "supplements"
                        },
                        new
                        {
                            Id = new Guid("26a46720-ae3a-43bd-b5de-2e2dd4048dee"),
                            Name = "Accessories",
                            Slug = "accessories"
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("OrderId", "ProductId", "ProductVariantId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02c314ef-6c38-41cd-ac00-aa3a986e3f46"),
                            CategoryId = new Guid("cb8ceb6a-6623-4937-a6c4-777b4b498e1e"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The three words that motivated generations of weightlifters are back! As worn by Bulgaria’s -85kg snatch record holder from the ‘90s, Georgi Gardev. Oversized fit.",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/WBN1.jpg",
                            Name = "Why Be Normal T-shirt",
                            Price = 40m,
                            Slug = "why-be-normal-tshirt",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("1dec9339-ab58-4186-90c3-c6eb7f971893"),
                            CategoryId = new Guid("cb8ceb6a-6623-4937-a6c4-777b4b498e1e"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The official t-shirt of Olympic Champion Karlos Nasar. Made in collaboration with the greatest weightlifter of a generation, the Nasar ‘I Win, You Lose’ T-shirt.",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/6_155b8e55-8336-438c-a966-fdec261cd0cb.jpg",
                            Name = "Nasar I Win, You Lose T-shirt",
                            Price = 45m,
                            Slug = "nasar-i-win-you-lose-tshirt",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("e28b6ccc-c7d5-49d6-95ae-1c6e665c6ced"),
                            CategoryId = new Guid("cb8ceb6a-6623-4937-a6c4-777b4b498e1e"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Celebrate the record-breaking power of Olympic Champion Karlos Nasar with this exclusive t-shirt. Featuring the iconic ‘404’ — marking the world and Olympic total record.",
                            IsPublished = true,
                            MainImageUrl = "https://karlosnasar.com/storage/products/371146981.jpg",
                            Name = "T-shirt 404",
                            Price = 30m,
                            Slug = "tshirt-404",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("96ddcde3-5ff2-4fd4-b685-f216945568a3"),
                            CategoryId = new Guid("6f026985-b5c2-4b05-9ac4-088b88982ec8"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The official t-shirt of Olympic Champion Karlos Nasar. Made in collaboration with the greatest weightlifter of a generation, the Nasar ‘I Win, You Lose’ Shorts",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/18_75ea3d05-1e8b-4fbc-af35-a41fb16930b3.jpg",
                            Name = "Nasar I Win, You Lose Shorts",
                            Price = 62.95m,
                            Slug = "nasar-i-win-you-lose-shorts",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("467ea21c-0fcf-4dde-801a-17e77ee4a5b2"),
                            CategoryId = new Guid("6f026985-b5c2-4b05-9ac4-088b88982ec8"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The official t-shirt of Olympic Champion Karlos Nasar. Made in collaboration with the greatest weightlifter of a generation, the Nasar ‘I Win, You Lose’ Leggings",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/13_2144736c-1165-42a7-87f7-c90db6a3c274.jpg",
                            Name = "Nasar I Win, You Lose Leggings",
                            Price = 70m,
                            Slug = "nasar-i-win-you-lose-leggings",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            CategoryId = new Guid("a9c9243a-aca9-4d3c-8f7a-4bdeb4578682"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "When Karlos Nasar shattered the world record, he did it in LUXIAOJUN lifters. That moment wasn’t just victory. It was domination. To celebrate his legacy and mindset, we present the Karlos Edition: built for lifters who don't just compete, they take over.",
                            IsPublished = true,
                            MainImageUrl = "https://luxiaojun.com/cdn/shop/files/LUXIAOJUN_PowerPro_Weightlifting_Shoes_Karlos_Edition_Pair.jpg",
                            Name = "LUXIAOJUN PowerPro Weightlifting Shoes (Karlos)",
                            Price = 195m,
                            Slug = "luxiaojun-powerpro-weightlifting-shoes-karlos",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("a8bcb2ba-bd47-4370-a443-505776baebb3"),
                            CategoryId = new Guid("f1f47314-cdc4-4104-a9f2-a2ccf38e9623"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Fuel your performance with Gold Standard 100% Whey — a premium protein powder built for muscle support and post-workout recovery. Featuring 24g of protein and 5.5g of BCAAs per serving, with whey protein isolate as the No. 1 ingredient.",
                            IsPublished = true,
                            MainImageUrl = "https://www.optimumnutrition.com/cdn/shop/files/on-1101490_Image_01.jpg",
                            Name = "GOLD STANDARD 100% WHEY",
                            Price = 99.99m,
                            Slug = "gold-standard-100-whey",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("c7f9f6ad-8512-49b0-bb48-980c3922fe60"),
                            CategoryId = new Guid("f1f47314-cdc4-4104-a9f2-a2ccf38e9623"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Boost your performance with Micronized Creatine Powder — designed to support muscle strength and power, explosive movements, and ATP recycling. Delivering 5g of creatine monohydrate per serving and stackable with Gold Standard 100% Whey for complete muscle support.",
                            IsPublished = true,
                            MainImageUrl = "https://www.optimumnutrition.com/cdn/shop/files/on-1102271_Image_01.png",
                            Name = "Micronized Creatine Powder",
                            Price = 30m,
                            Slug = "micronized-creatine-powder",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = new Guid("c4ed28d4-92cb-4532-8949-044be6a66e28"),
                            CategoryId = new Guid("26a46720-ae3a-43bd-b5de-2e2dd4048dee"),
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Designed by Olympic Champion Karlos Nasar to elevate your training. These classic quick-release straps offer performance and durability with Karlos’s signature branding.",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/nasar_house_1.jpg",
                            Name = "Nasar House Straps",
                            Price = 26m,
                            Slug = "nasar-house-straps",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75feaf94-8a87-495e-910e-01276c94d0c8"),
                            IsDeleted = false,
                            ProductId = new Guid("02c314ef-6c38-41cd-ac00-aa3a986e3f46"),
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("fac660c5-b882-426d-bc27-5c20a6634402"),
                            IsDeleted = false,
                            ProductId = new Guid("02c314ef-6c38-41cd-ac00-aa3a986e3f46"),
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("4c8177a6-5c5d-4ce5-9955-65626c6262a3"),
                            IsDeleted = false,
                            ProductId = new Guid("02c314ef-6c38-41cd-ac00-aa3a986e3f46"),
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("91367123-74d9-435e-91ce-98debdeaf9ff"),
                            IsDeleted = false,
                            ProductId = new Guid("02c314ef-6c38-41cd-ac00-aa3a986e3f46"),
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("430e4616-4746-4fdb-a227-5584361edd68"),
                            IsDeleted = false,
                            ProductId = new Guid("1dec9339-ab58-4186-90c3-c6eb7f971893"),
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("21f64de2-0991-4363-baff-16aa1b8064f4"),
                            IsDeleted = false,
                            ProductId = new Guid("1dec9339-ab58-4186-90c3-c6eb7f971893"),
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("0135a402-3bfe-4cb0-9ae6-96a18e8dadef"),
                            IsDeleted = false,
                            ProductId = new Guid("1dec9339-ab58-4186-90c3-c6eb7f971893"),
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("38657209-0631-4310-8839-7a8badc05367"),
                            IsDeleted = false,
                            ProductId = new Guid("1dec9339-ab58-4186-90c3-c6eb7f971893"),
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("4147f8f0-6c0a-4005-a916-20cef7685120"),
                            IsDeleted = false,
                            ProductId = new Guid("e28b6ccc-c7d5-49d6-95ae-1c6e665c6ced"),
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("d57befc8-55a9-41c1-b5f6-7a47381de37f"),
                            IsDeleted = false,
                            ProductId = new Guid("e28b6ccc-c7d5-49d6-95ae-1c6e665c6ced"),
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("e2994b78-47b5-4aaa-afec-3d1a093b5a43"),
                            IsDeleted = false,
                            ProductId = new Guid("e28b6ccc-c7d5-49d6-95ae-1c6e665c6ced"),
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("389068f2-e83d-4d11-8d7c-db2760966585"),
                            IsDeleted = false,
                            ProductId = new Guid("e28b6ccc-c7d5-49d6-95ae-1c6e665c6ced"),
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("c3adf1e3-384b-4fbd-9601-4ad589f5cd8d"),
                            IsDeleted = false,
                            ProductId = new Guid("96ddcde3-5ff2-4fd4-b685-f216945568a3"),
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("6f665e33-c4a9-4548-aa78-accdad51909a"),
                            IsDeleted = false,
                            ProductId = new Guid("96ddcde3-5ff2-4fd4-b685-f216945568a3"),
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("7f8adfae-2530-4920-b71c-4a58ce6a428d"),
                            IsDeleted = false,
                            ProductId = new Guid("96ddcde3-5ff2-4fd4-b685-f216945568a3"),
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("51b55327-3e64-406b-b2b6-341bb4562ce1"),
                            IsDeleted = false,
                            ProductId = new Guid("96ddcde3-5ff2-4fd4-b685-f216945568a3"),
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("3415ca9a-14ab-44a8-8cfe-cfbaa687fddd"),
                            IsDeleted = false,
                            ProductId = new Guid("467ea21c-0fcf-4dde-801a-17e77ee4a5b2"),
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("f94fc295-e46a-41f1-b016-0055ebfbde22"),
                            IsDeleted = false,
                            ProductId = new Guid("467ea21c-0fcf-4dde-801a-17e77ee4a5b2"),
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("3c793526-7537-49f4-8fff-aa25dd25ad48"),
                            IsDeleted = false,
                            ProductId = new Guid("467ea21c-0fcf-4dde-801a-17e77ee4a5b2"),
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("53c5dc85-a298-4627-b65a-bcae0f94682a"),
                            IsDeleted = false,
                            ProductId = new Guid("467ea21c-0fcf-4dde-801a-17e77ee4a5b2"),
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = new Guid("b347cf2f-c0cd-416f-a330-e75614b11c60"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 38 EU"
                        },
                        new
                        {
                            Id = new Guid("2e64045a-0c1b-4122-9100-14df928f025a"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 39 EU"
                        },
                        new
                        {
                            Id = new Guid("077ce4ee-d228-421e-8c67-b6936a511e36"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 40 EU"
                        },
                        new
                        {
                            Id = new Guid("8c3c3fd0-d1cb-49e6-8d2b-e7c04a059917"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 41 EU"
                        },
                        new
                        {
                            Id = new Guid("0bedd38e-210c-4552-9de8-8ba385901981"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 42 EU"
                        },
                        new
                        {
                            Id = new Guid("8a2e6649-bd1a-4147-acf0-5e20405d315d"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 43 EU"
                        },
                        new
                        {
                            Id = new Guid("1cb5d36e-0e0c-401e-a6dc-a1d287e8afb6"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 44 EU"
                        },
                        new
                        {
                            Id = new Guid("04eb7d5e-ad31-417a-8544-470f559583c2"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 45 EU"
                        },
                        new
                        {
                            Id = new Guid("2ceab2fb-6d88-421a-98b4-ba293000fa8e"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 46 EU"
                        },
                        new
                        {
                            Id = new Guid("694e0600-e0ca-456a-9ec9-9dd3b25651d9"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 47 EU"
                        },
                        new
                        {
                            Id = new Guid("7e905a23-8f10-4074-aade-7c29693e6e93"),
                            IsDeleted = false,
                            ProductId = new Guid("ac8a1ca5-d799-435f-8b6b-f4161ac2e284"),
                            VariantName = "Size 48 EU"
                        },
                        new
                        {
                            Id = new Guid("7dcf0d49-527c-4c7a-9cd6-89ce6cab3a26"),
                            IsDeleted = false,
                            Price = 99.99m,
                            ProductId = new Guid("a8bcb2ba-bd47-4370-a443-505776baebb3"),
                            VariantName = "Double Rich Chocolate / 2.26KG"
                        },
                        new
                        {
                            Id = new Guid("7b0f801b-5af3-4c03-9406-e4262f5e3c16"),
                            IsDeleted = false,
                            Price = 30m,
                            ProductId = new Guid("c7f9f6ad-8512-49b0-bb48-980c3922fe60"),
                            VariantName = "Unflavored / 317g"
                        },
                        new
                        {
                            Id = new Guid("21b6185b-b955-46c4-a48f-1e8b037fa265"),
                            IsDeleted = false,
                            ProductId = new Guid("c4ed28d4-92cb-4532-8949-044be6a66e28"),
                            VariantName = "Color: Black and Green"
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d333796b-4dd0-410c-92fd-481a6dc3fd0d"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("e444796b-4dd0-410c-92fd-481a6dc3fd0d"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("06313180-fa45-42b5-ac33-1333f673455d"),
                            RoleId = new Guid("d333796b-4dd0-410c-92fd-481a6dc3fd0d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.CartItem", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Order", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.OrderItem", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Product", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ProductVariant", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ShoppingCart", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
